buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Das Android-Gradle-Plugin, das Gradle beibringt, wie man Android-APKs baut
        classpath 'com.android.tools.build:gradle:8.11.2'
    }
}

apply plugin: 'com.android.application'

android {
    // Hier den Package-Namen aus Ihrer AndroidManifest.xml eintragen:
    namespace 'at.gaeckler.GpxMotorCycle'

    compileSdk 36

    defaultConfig {
        applicationId "at.gaeckler.GpxMotorCycle"
        minSdk 30
        targetSdk 36
        versionCode 6
        versionName "07.28"
    }

    sourceSets {
        main {
            // Sagt Gradle, dass die Dateiverzeichnisse aus dem alten ADT-Layout stammen:
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }
}